# Configuration file
# Instruction : 
# - endpoint : set the URL address where you execute your SPARQL query
# - isql_virtuoso_path : set where is the isql of Virtuoso
# - site : set the number of site
# - queries : set the number of queries you want to keep from all gMark/WatDiv queries
# - run : set the number of run you want
# - clean_after : set if you want to execute ./scripts/digestuoso.sh after each run
# - use_watdiv : set if you want to use WatDiv queries or not
# - use_fixator : set if you want to use ./scripts/fixator.py or not
# - sameas_proba : set the probability of replication for each entities to create sameAs predicates between the original entity and the replicate entity
# - data_distribution : set the data distribution for each site
# - shared_types : set entities who are shared between site, and so are in federated_shop

endpoint: "http://localhost:8890/sparql"
isql_virtuoso_path: '/home/ubuntu/virtuoso-opensource/bin/isql'
site: 10
queries: 20
clean_after: False
use_watdiv: False
use_fixator: True

sameas_proba:
  ClassicalMusicConcert: 0.6
  MusicConcert: 0.4
  HitMusicConcert: 0.8
  MusicAlbum: 0.5
  ClassicMusicAlbum: 0.7
  HitMusicAlbum: 0.7
  Movie: 0.4
  ClassicMovie: 0.6
  TopMovie: 0.4
  AnimatedMovie: 0.2
  ShortMovie: 0.5
  LongMovie: 0.5
  Book: 0.7
  NewsArticleBook: 0.3
  ArticleBook: 0.4
  NovelBook: 0.3
  ShortStoryBook: 0.3
  EncyclopediaBook: 0.34
  OtherProduct: 0.5

data_distribution:
  choosen_type: "gaussian"
  types:
      "zipfian":
            alpha: 1.22
            multiplicator: 10
      "gaussian":
            mu: 600000
            sigma: 200000
      "uniform":
            min: 1000
            max: 10000

shared_types: ['Genre', 'SubGenre', 'Topic', 'HotTopic', 'City', 'Country', 'Language', 'Role', 'AgeGroup', 'Gender']
