# Configuration file
# Instruction : 
# - endpoint : set the URL address where you execute your SPARQL query
# - isql_virtuoso_path : set where is the isql of Virtuoso
# - site : set the number of site
# - queries : set the number of queries you want to keep from all gMark/WatDiv queries
# - run : set the number of run you want
# - clean_after : set if you want to execute ./scripts/digestuoso.sh after each run
# - use_watdiv : set if you want to use WatDiv queries or not
# - improve_data_coherency : set if you want to use ./scripts/improve_data_coherency.py or not
# - sameas_proba : set the probability of replication for each entities to create sameAs predicates between the original entity and the replicate entity
# - data_distribution : set the data distribution for each site
# - shared_types : set entities who are shared between site, and so are in federated_shop

endpoint: "http://localhost:8890/sparql"
isql_virtuoso_path: '/Applications/Virtuoso_Open_Source_Edition_v7.2.app/Contents/virtuoso-opensource/bin/isql'
site: 3
queries: 10
run: 3
federapp_query_timeout: 3600
clean_after: True
use_watdiv: False
improve_data_coherency: True

sameas_proba:
  ClassicalMusicConcert: 0.6
  MusicConcert: 0.4
  HitMusicConcert: 0.8
  MusicAlbum: 0.5
  ClassicMusicAlbum: 0.7
  HitMusicAlbum: 0.7
  Movie: 0.4
  ClassicMovie: 0.6
  TopMovie: 0.4
  AnimatedMovie: 0.2
  ShortMovie: 0.5
  LongMovie: 0.5
  Book: 0.7
  NewsArticleBook: 0.3
  ArticleBook: 0.4
  NovelBook: 0.3
  ShortStoryBook: 0.3
  EncyclopediaBook: 0.34
  OtherProduct: 0.5

data_distribution:
  nodes_threshold: 10000
  choosen_type: "uniform"
  types:
      "zipfian":
            alpha: 1.22
            multiplicator: 10
      "gaussian":
            mu: 600000
            sigma: 200000
      "uniform":
            min: 1000
            max: 2000

replicate_distribution:
  ClassicalMusicConcert:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  MusicConcert:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  HitMusicConcert:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  MusicAlbum:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  ClassicMusicAlbum:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  HitMusicAlbum:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  Movie:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  ClassicMovie:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  TopMovie:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  AnimatedMovie:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  ShortMovie:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  LongMovie:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  Book:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  NewsArticleBook:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  ArticleBook:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  NovelBook:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  ShortStoryBook:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  EncyclopediaBook:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5
  OtherProduct:
    choosen_type: "uniform"
    types:
      "uniform":
        min: 1
        max: 5

shared_types: ['Genre', 'SubGenre', 'Topic', 'HotTopic', 'City', 'Country', 'Language', 'Role', 'AgeGroup', 'Gender']
