# Configuration file
# Instruction : 
# - endpoint : set the URL address where you execute your SPARQL query
# - isql_virtuoso_path : set where is the isql of Virtuoso
# - site : set the number of site
# - queries : set the number of queries you want to keep from all gMark/WatDiv queries
# - run : set the number of run you want
# - clean_after : set if you want to execute ./scripts/digestuoso.sh after each run
# - use_watdiv : set if you want to use WatDiv queries or not
# - use_fixator : set if you want to use ./scripts/fixator.py or not

endpoint: "http://localhost:8890/sparql"
isql_virtuoso_path: '/home/ubuntu/virtuoso-opensource/bin/isql'
site: 100
queries: 5
run: 1
clean_after: False
use_watdiv: False
use_fixator: False