endpoint: "http://localhost:8890/sparql"
isql_virtuoso_path: '/home/ubuntu/virtuoso-opensource/bin/isql'

site: 10
queries: 20
clean_after: False
use_watdiv: False
use_fixator: True

sameas_proba:
  ClassicalMusicConcert: 0.3
  MusicConcert: 0.2
  HitMusicConcert: 0.4
  MusicAlbum: 0.5
  ClassicMusicAlbum: 0.1
  HitMusicAlbum: 0.4
  Movie: 0.2
  ClassicMovie: 0.2
  TopMovie: 0.3
  AnimatedMovie: 0.1
  ShortMovie: 0.5
  LongMovie: 0.5
  Book: 0.1
  NewsArticleBook: 0.3
  ArticleBook: 0.4
  NovelBook: 0.3
  ShortStoryBook: 0.3
  EncyclopediaBook: 0.2
  OtherProduct: 0.5

data_distribution:
  choosen_type: "uniform"
  types:
      "zipfian":
            alpha: 1.65
            multiplicator: 10
      "gaussian":
            mu: 6000
            sigma: 2000
      "uniform":
            min: 1000
            max: 10000

shared_types: ['Genre', 'SubGenre', 'Topic', 'HotTopic', 'City', 'Country', 'Language', 'Role', 'AgeGroup', 'Gender']
