endpoint: "http://localhost:8890/sparql" #Following this tutorial to match http://localhost:8890/sparql from Windows with current endpoint from WSL : https://devdojo.com/mvnarendrareddy/access-windows-localhost-from-wsl2
isql_virtuoso_path: '/home/ubuntu/virtuoso-opensource/bin/isql'
site: 100
queries: 5
run: 1
clean_after: False
use_watdiv: False
use_fixator: False