= SPARQL Federated Benchmark
GICQUEL Mathieu; LE CROM Yotlan
:toc:

== Meaning

This benchmark create automatcly **RDF data** and **SPARQL queries** based on link:https://github.com/gbagan/gmark[gMark]. Indeed, you need to set whatever you want in the setting file `lib/gmark/use-cases/shop.xml`. Moreover, you can set additionnal setting in the setting file `configuration.yaml`. To conclude on setting, you can set the number of site in the file `multiple-run.sh`.

== Approaches

=== Data Partitioning

Our first idea is to do some data partitioning. After doing Hash Partitioning who was not very logical about the schema of a federated shop, this approach birth. Indeed, we decide to spread a source site above the whole data from a Retailer. To do this, we use **CONSTRUCT SPARQL queries**. The following branch is the subject of this idea :

link:https://github.com/MathieuGicquel/federated-benchmark/tree/data_partitioning[data_partitioning]

=== Data Alignment

Our second idea is to do data alignment. Indeed, in this case, we generate 1 gMark per site instead of the previous idea, who we generated 1 gMark for all site. In this case, is very simple to spread the source site, because all data of a site is in his data file. Moreover, is easier to add sameAs predicate. The following branch is the subject of this idea :

link:https://github.com/MathieuGicquel/federated-benchmark/tree/data_alignment[data_alignment]